// Code generated by MockGen. DO NOT EDIT.
// Source: autoiso_api_service.go
//
// Generated by this command:
//
//	mockgen -source autoiso_api_service.go -destination mocks/autoiso_api_service_mock.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/DIMO-Network/device-definitions-api/internal/core/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAutoIsoAPIService is a mock of AutoIsoAPIService interface.
type MockAutoIsoAPIService struct {
	ctrl     *gomock.Controller
	recorder *MockAutoIsoAPIServiceMockRecorder
}

// MockAutoIsoAPIServiceMockRecorder is the mock recorder for MockAutoIsoAPIService.
type MockAutoIsoAPIServiceMockRecorder struct {
	mock *MockAutoIsoAPIService
}

// NewMockAutoIsoAPIService creates a new mock instance.
func NewMockAutoIsoAPIService(ctrl *gomock.Controller) *MockAutoIsoAPIService {
	mock := &MockAutoIsoAPIService{ctrl: ctrl}
	mock.recorder = &MockAutoIsoAPIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAutoIsoAPIService) EXPECT() *MockAutoIsoAPIServiceMockRecorder {
	return m.recorder
}

// GetVIN mocks base method.
func (m *MockAutoIsoAPIService) GetVIN(vin string) (*models.AutoIsoVINResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVIN", vin)
	ret0, _ := ret[0].(*models.AutoIsoVINResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVIN indicates an expected call of GetVIN.
func (mr *MockAutoIsoAPIServiceMockRecorder) GetVIN(vin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVIN", reflect.TypeOf((*MockAutoIsoAPIService)(nil).GetVIN), vin)
}
