// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infrastructure/gateways/device_definition_catalog_service.go
//
// Generated by this command:
//
//	mockgen -source internal/infrastructure/gateways/device_definition_catalog_service.go -destination internal/infrastructure/gateways/mocks/device_definition_catalog_service_mock.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	big "math/big"
	reflect "reflect"

	models "github.com/DIMO-Network/device-definitions-api/internal/core/models"
	types "github.com/aarondl/sqlboiler/v4/types"
	gomock "go.uber.org/mock/gomock"
)

// MockDeviceDefinitionCatalogService is a mock of DeviceDefinitionCatalogService interface.
type MockDeviceDefinitionCatalogService struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceDefinitionCatalogServiceMockRecorder
	isgomock struct{}
}

// MockDeviceDefinitionCatalogServiceMockRecorder is the mock recorder for MockDeviceDefinitionCatalogService.
type MockDeviceDefinitionCatalogServiceMockRecorder struct {
	mock *MockDeviceDefinitionCatalogService
}

// NewMockDeviceDefinitionCatalogService creates a new mock instance.
func NewMockDeviceDefinitionCatalogService(ctrl *gomock.Controller) *MockDeviceDefinitionCatalogService {
	mock := &MockDeviceDefinitionCatalogService{ctrl: ctrl}
	mock.recorder = &MockDeviceDefinitionCatalogServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceDefinitionCatalogService) EXPECT() *MockDeviceDefinitionCatalogServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDeviceDefinitionCatalogService) Create(ctx context.Context, manufacturerName string, dd models.DeviceDefinitionTablelandModel) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, manufacturerName, dd)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDeviceDefinitionCatalogServiceMockRecorder) Create(ctx, manufacturerName, dd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeviceDefinitionCatalogService)(nil).Create), ctx, manufacturerName, dd)
}

// Delete mocks base method.
func (m *MockDeviceDefinitionCatalogService) Delete(ctx context.Context, manufacturerName, id string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, manufacturerName, id)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockDeviceDefinitionCatalogServiceMockRecorder) Delete(ctx, manufacturerName, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeviceDefinitionCatalogService)(nil).Delete), ctx, manufacturerName, id)
}

// GetDefinition mocks base method.
func (m *MockDeviceDefinitionCatalogService) GetDefinition(ctx context.Context, manufacturerID *big.Int, ID string) (*models.DeviceDefinitionTablelandModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefinition", ctx, manufacturerID, ID)
	ret0, _ := ret[0].(*models.DeviceDefinitionTablelandModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefinition indicates an expected call of GetDefinition.
func (mr *MockDeviceDefinitionCatalogServiceMockRecorder) GetDefinition(ctx, manufacturerID, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefinition", reflect.TypeOf((*MockDeviceDefinitionCatalogService)(nil).GetDefinition), ctx, manufacturerID, ID)
}

// GetDefinitionByID mocks base method.
func (m *MockDeviceDefinitionCatalogService) GetDefinitionByID(ctx context.Context, ID string) (*models.DeviceDefinitionTablelandModel, *big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefinitionByID", ctx, ID)
	ret0, _ := ret[0].(*models.DeviceDefinitionTablelandModel)
	ret1, _ := ret[1].(*big.Int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDefinitionByID indicates an expected call of GetDefinitionByID.
func (mr *MockDeviceDefinitionCatalogServiceMockRecorder) GetDefinitionByID(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefinitionByID", reflect.TypeOf((*MockDeviceDefinitionCatalogService)(nil).GetDefinitionByID), ctx, ID)
}

// GetDeviceDefinitionByID mocks base method.
func (m *MockDeviceDefinitionCatalogService) GetDeviceDefinitionByID(ctx context.Context, manufacturerID *big.Int, ID string) (*models.DeviceDefinitionTablelandModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceDefinitionByID", ctx, manufacturerID, ID)
	ret0, _ := ret[0].(*models.DeviceDefinitionTablelandModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceDefinitionByID indicates an expected call of GetDeviceDefinitionByID.
func (mr *MockDeviceDefinitionCatalogServiceMockRecorder) GetDeviceDefinitionByID(ctx, manufacturerID, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceDefinitionByID", reflect.TypeOf((*MockDeviceDefinitionCatalogService)(nil).GetDeviceDefinitionByID), ctx, manufacturerID, ID)
}

// GetDeviceDefinitions mocks base method.
func (m *MockDeviceDefinitionCatalogService) GetDeviceDefinitions(ctx context.Context, manufacturerID types.NullDecimal, ID, model string, year int, pageIndex, pageSize int32) ([]models.DeviceDefinitionTablelandModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceDefinitions", ctx, manufacturerID, ID, model, year, pageIndex, pageSize)
	ret0, _ := ret[0].([]models.DeviceDefinitionTablelandModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceDefinitions indicates an expected call of GetDeviceDefinitions.
func (mr *MockDeviceDefinitionCatalogServiceMockRecorder) GetDeviceDefinitions(ctx, manufacturerID, ID, model, year, pageIndex, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceDefinitions", reflect.TypeOf((*MockDeviceDefinitionCatalogService)(nil).GetDeviceDefinitions), ctx, manufacturerID, ID, model, year, pageIndex, pageSize)
}

// GetManufacturer mocks base method.
func (m *MockDeviceDefinitionCatalogService) GetManufacturer(manufacturerSlug string) (*models.Manufacturer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetManufacturer", manufacturerSlug)
	ret0, _ := ret[0].(*models.Manufacturer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetManufacturer indicates an expected call of GetManufacturer.
func (mr *MockDeviceDefinitionCatalogServiceMockRecorder) GetManufacturer(manufacturerSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManufacturer", reflect.TypeOf((*MockDeviceDefinitionCatalogService)(nil).GetManufacturer), manufacturerSlug)
}

// GetManufacturerNameByID mocks base method.
func (m *MockDeviceDefinitionCatalogService) GetManufacturerNameByID(ctx context.Context, manufacturerID *big.Int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetManufacturerNameByID", ctx, manufacturerID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetManufacturerNameByID indicates an expected call of GetManufacturerNameByID.
func (mr *MockDeviceDefinitionCatalogServiceMockRecorder) GetManufacturerNameByID(ctx, manufacturerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManufacturerNameByID", reflect.TypeOf((*MockDeviceDefinitionCatalogService)(nil).GetManufacturerNameByID), ctx, manufacturerID)
}

// QueryDefinitionsByManufacturer mocks base method.
func (m *MockDeviceDefinitionCatalogService) QueryDefinitionsByManufacturer(ctx context.Context, manufacturerID, pageIndex int) ([]models.DeviceDefinitionTablelandModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryDefinitionsByManufacturer", ctx, manufacturerID, pageIndex)
	ret0, _ := ret[0].([]models.DeviceDefinitionTablelandModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryDefinitionsByManufacturer indicates an expected call of QueryDefinitionsByManufacturer.
func (mr *MockDeviceDefinitionCatalogServiceMockRecorder) QueryDefinitionsByManufacturer(ctx, manufacturerID, pageIndex any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryDefinitionsByManufacturer", reflect.TypeOf((*MockDeviceDefinitionCatalogService)(nil).QueryDefinitionsByManufacturer), ctx, manufacturerID, pageIndex)
}

// Update mocks base method.
func (m *MockDeviceDefinitionCatalogService) Update(ctx context.Context, manufacturerName string, input models.DeviceDefinitionUpdateInput) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, manufacturerName, input)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDeviceDefinitionCatalogServiceMockRecorder) Update(ctx, manufacturerName, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDeviceDefinitionCatalogService)(nil).Update), ctx, manufacturerName, input)
}
