version: "2"
linters:
  enable:
    - prealloc
    - revive
    - tagliatelle
    - zerologlint
  settings:
    tagliatelle:
      case:
        rules:
          json: camel
          yaml: upperSnake
        use-field-name: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
          - tagliatelle
        path: internal/infrastructure/gateways/datgroup_api_service.go
    paths:
      - pkg/grpc
      - third_party$
      - builtin$
      - examples$
issues:
  fix: true
formatters:
  enable:
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/DIMO-Network/device-definitions-api)
        - blank
        - dot
      custom-order: false
  exclusions:
    generated: lax
    paths:
      - pkg/grpc
      - third_party$
      - builtin$
      - examples$
