# db for local dev
version: '3.9'

services:
  postgresql:
    image: postgres:12.9-alpine # matches version used on aws environments
    container_name: pg-device-definitions
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dimo
      - POSTGRES_PASSWORD=dimo
      - POSTGRES_DB=device_definitions_api
      
  jaeger:
    image: jaegertracing/all-in-one:1.22.0
    platform: linux/amd64
    container_name: jaeger-device-definitions
    ports:
      - 14268:14268 # jaeger-collector HTTP server (tracer provider)
      - 16686:16686 # HTTP server (browser UI)

  ipfs:
    image: ipfs/go-ipfs:latest
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata
    volumes:
      - ./data/ipfs:/ipfsdata
    ports:
      - "4001:4001"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:5001:5001"