# db for local dev
version: '3.9'

services:
  postgresql:
    image: postgres:12.9-alpine # matches version used on aws environments
    container_name: pg-device-definitions
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dimo
      - POSTGRES_PASSWORD=dimo
      - POSTGRES_DB=device_definitions_api
    volumes:
      - postgresdb:/var/lib/postgresql/data:delegated

  ipfs:
    image: ipfs/go-ipfs:latest
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata
    volumes:
      - ./data/ipfs:/ipfsdata
    ports:
      - "4001:4001"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:5001:5001"

  redis:
    image: redis:6.2 # latest version on ElastiCache
    container_name: redis-device-definitions-api
    ports:
      - "6379:6379"
    volumes:
      - redis:/data:delegated

volumes:
  postgresdb:
    driver: local
  redis:
    driver: local

networks:
  elastic:
    driver: bridge