# db for local dev
version: "3.9"

services:
  postgresql:
    image: postgres:16.6-alpine # matches version used on aws environments
    container_name: pg-device-definitions
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dimo
      - POSTGRES_PASSWORD=dimo
      - POSTGRES_DB=device_definitions_api
    volumes:
      - postgresdb:/var/lib/postgresql/data:delegated

  ipfs:
    image: ipfs/go-ipfs:latest
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata
    volumes:
      - ./data/ipfs:/ipfsdata
    ports:
      - "4001:4001"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:5001:5001"

  redis:
    image: redis:6.2 # latest version on ElastiCache
    container_name: redis-device-definitions-api
    ports:
      - "6379:6379"
    volumes:
      - redis:/data:delegated

  typesense:
    image: typesense/typesense:26.0
    container_name: typesense-device-definitions-api
    ports:
      - "8108:8108"
    volumes:
      - typesense:/data:delegated
    command: ["--data-dir", "/data", "--api-key=xyz"]

#  zookeeper:
#    image: 'bitnami/zookeeper:latest'
#    ports:
#      - '2181:2181'
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#  # Does not persist anything!
#  kafka:
#    image: 'bitnami/kafka:latest'
#    ports:
#      - '9092:9092'
#    environment:
#      - KAFKA_BROKER_ID=1
#      - KAFKA_LISTENERS=PLAINTEXT://:9092
#      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
#      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper

volumes:
  postgresdb:
    driver: local
  redis:
    driver: local
  typesense:
    driver: local

networks:
  elastic:
    driver: bridge
