ENVIRONMENT: local
PORT: 3000
LOG_LEVEL: info
DB_USER: dimo
DB_PASSWORD: dimo
DB_PORT: 5432
DB_HOST: localhost
DB_NAME: device_definitions_api
DB_MAX_OPEN_CONNECTIONS: 5
DB_MAX_IDLE_CONNECTIONS: 5
SERVICE_NAME: device-definitions-api
SERVICE_VERSION: "1.0.0"
GRPC_PORT: 9000
TRACE_MONITOR_VIEW: http://localhost:14268/api/traces