ENVIRONMENT: local
LOG_LEVEL: info
PORT: 3000
GRPC_PORT: 9000
MONITORING_PORT: 8888
SERVICE_NAME: device-definitions-api
SERVICE_VERSION: "1.0.0"
DB:
  USER: dimo
  PASSWORD: dimo
  PORT: 5432
  HOST: localhost
  NAME: device_definitions_api
  MAX_OPEN_CONNECTIONS: 5
  MAX_IDLE_CONNECTIONS: 5
REDIS:
  URL: localhost:6379
  PASSWORD:
  TLS: false
  KEY_PREFIX: definitions-api
TRACE_MONITOR_VIEW: http://localhost:14268/api/traces
IPFS_NODE_ENDPOINT: http://localhost:5001
DRIVLY_VIN_API_URL: https://vin.dev.driv.ly
DRIVLY_OFFER_API_URL: https://offers.dev.driv.ly
DRIVLY_API_KEY: xxx
ELASTIC_SEARCH_APP_SEARCH_HOST: http://localhost:9200
ELASTIC_SEARCH_APP_SEARCH_TOKEN: private-
ELASTIC_SEARCH_DEVICE_STATUS_HOST: http://localhost:9200
ELASTIC_SEARCH_DEVICE_STATUS_TOKEN:
NHTSA_RECALLS_FILE_URL: https://static.nhtsa.gov/odi/ffdd/rcl/FLAT_RCL.zip
FUEL_API_VEHICLES_ENDPOINT:
FUEL_API_IMAGES_ENDPOINT:
FUEL_API_KEY:
VINCARIO_API_URL: https://api.vindecoder.eu/3.2
VINCARIO_API_KEY: xxx
VINCARIO_API_SECRET: xxx
DAT_GROUP_URL: https://www.datgroup.com/DATECodeSelection/services/VehicleIdentificationService
DAT_GROUP_AUTHURL: https://www.datgroup.com/myClaim/soap/v2/MyClaimExternalAuthenticationService
DAT_GROUP_CUSTOMER_LOGIN: xxx
DAT_GROUP_CUSTOMER_NUMBER: xxx
DAT_GROUP_CUSTOMER_PASSWORD: xxx
DAT_GROUP_INTERFACE_PARTNER_NUMBER: xxx
DAT_GROUP_INTERFACE_PARTNER_SIGNATURE: xxx
# Hardhat default port.
ETHEREUM_RPC_URL: http://127.0.0.1:8545
# Use the next variable. Never use this in production!
PRIVATE_KEY_MODE: true
# localhost Private key for default Hardhat account 0. Well-known.
SENDER_PRIVATE_KEY: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
ETHEREUM_REGISTRY_ADDRESS: 0xdc64a140aa3e981100a9beca4e685f962f0cf6c9
# Send transaction to etherum network
ETHEREUM_SEND_TRANSACTION: true
TABLELAND_API_GATEWAY: http://localhost:8080/
SEARCH_SERVICE_API_URL: http://localhost:8108/
SEARCH_SERVICE_API_KEY: xyz
SEARCH_SERVICE_DEVICE_DEFINITION_INDEX: definitions_dev
JAPAN17_VIN_USER: ''
JAPAN17_VIN_PASSWORD: ''