// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	DeviceDefinitions   string
	DeviceIntegrations  string
	DeviceMakes         string
	DeviceNhtsaRecalls  string
	DeviceStyles        string
	DeviceTypes         string
	Images              string
	IntegrationFeatures string
	Integrations        string
	Reviews             string
	VinNumbers          string
	Wmis                string
}{
	DeviceDefinitions:   "device_definitions",
	DeviceIntegrations:  "device_integrations",
	DeviceMakes:         "device_makes",
	DeviceNhtsaRecalls:  "device_nhtsa_recalls",
	DeviceStyles:        "device_styles",
	DeviceTypes:         "device_types",
	Images:              "images",
	IntegrationFeatures: "integration_features",
	Integrations:        "integrations",
	Reviews:             "reviews",
	VinNumbers:          "vin_numbers",
	Wmis:                "wmis",
}
