// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	DeviceDefinitions   string
	DeviceIntegrations  string
	DeviceMakes         string
	DeviceStyles        string
	IntegrationFeatures string
	Integrations        string
}{
	DeviceDefinitions:   "device_definitions",
	DeviceIntegrations:  "device_integrations",
	DeviceMakes:         "device_makes",
	DeviceStyles:        "device_styles",
	IntegrationFeatures: "integration_features",
	Integrations:        "integrations",
}
