// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	DefinitionTransactions string
	DeviceDefinitions      string
	DeviceIntegrations     string
	DeviceMakes            string
	DeviceStyles           string
	DeviceTypes            string
	Images                 string
	IntegrationFeatures    string
	Integrations           string
	VinNumbers             string
	Wmis                   string
}{
	DefinitionTransactions: "definition_transactions",
	DeviceDefinitions:      "device_definitions",
	DeviceIntegrations:     "device_integrations",
	DeviceMakes:            "device_makes",
	DeviceStyles:           "device_styles",
	DeviceTypes:            "device_types",
	Images:                 "images",
	IntegrationFeatures:    "integration_features",
	Integrations:           "integrations",
	VinNumbers:             "vin_numbers",
	Wmis:                   "wmis",
}
