apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "device-definitions-api.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  data:
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/ethereum/rpc_url
    secretKey: ETHEREUM_RPC_URL
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/aws/access_key_id
    secretKey: AWS_ACCESS_KEY_ID
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/aws/secret_access_key
    secretKey: AWS_SECRET_ACCESS_KEY
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/kms/key_id
    secretKey: KMS_KEY_ID
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/db/host
    secretKey: DB_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/db/user
    secretKey: DB_USER
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/db/pass
    secretKey: DB_PASSWORD
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/redis/host
    secretKey: REDIS_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/redis/url
    secretKey: REDIS_URL
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/redis/password
    secretKey: REDIS_PASSWORD
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/elastic/device_status/host
    secretKey: ELASTIC_SEARCH_DEVICE_STATUS_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/elastic/device_status/token
    secretKey: ELASTIC_SEARCH_DEVICE_STATUS_TOKEN
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/drivly/apikey
    secretKey: DRIVLY_API_KEY
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/fuelapi/apikey
    secretKey: FUEL_API_KEY
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/vincario/apikey
    secretKey: VINCARIO_API_KEY
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/vincario/apisecret
    secretKey: VINCARIO_API_SECRET
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/autoiso/apiuid
    secretKey: AUTO_ISO_API_UID
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/autoiso/apikey
    secretKey: AUTO_ISO_API_KEY
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/datgroup/customerlogin
    secretKey: DAT_GROUP_CUSTOMER_LOGIN
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/datgroup/customernumber
    secretKey: DAT_GROUP_CUSTOMER_NUMBER
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/datgroup/partnersignature
    secretKey: DAT_GROUP_INTERFACE_PARTNER_SIGNATURE
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/datgroup/customersignature
    secretKey: DAT_GROUP_CUSTOMER_SIGNATURE
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/typesense/apikey
    secretKey: SEARCH_SERVICE_API_KEY
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/typesense/apiurl
    secretKey: SEARCH_SERVICE_API_URL
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/polygonscan/apikey
    secretKey: POLYGON_SCAN_API_KEY
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/googlesheets/credentials
    secretKey: GOOGLE_SHEETS_CREDENTIALS
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/17vin/user
    secretKey: JAPAN17_VIN_USER
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/17vin/password
    secretKey: JAPAN17_VIN_PASSWORD
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/carvx/userid
    secretKey: CAR_VX_USER_ID
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/carvx/apikey
    secretKey: CAR_VX_API_KEY
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-secret-store
  target:
    name: {{ include "device-definitions-api.fullname" . }}-secret
    template:
      metadata: {}
