apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "device-definitions-api.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  data:
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/db/host
    secretKey: DB_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/db/user
    secretKey: DB_USER
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/db/pass
    secretKey: DB_PASSWORD
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/redis/host
    secretKey: REDIS_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/redis/url
    secretKey: REDIS_URL
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/redis/password
    secretKey: REDIS_PASSWORD
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/elastic/appsearch/host
    secretKey: ELASTIC_SEARCH_APP_SEARCH_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/elastic/appsearch/token
    secretKey: ELASTIC_SEARCH_APP_SEARCH_TOKEN
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/elastic/device_status/host
    secretKey: ELASTIC_SEARCH_DEVICE_STATUS_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/elastic/device_status/token
    secretKey: ELASTIC_SEARCH_DEVICE_STATUS_TOKEN
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/drivly/apikey
    secretKey: DRIVLY_API_KEY
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/fuelapi/apikey
    secretKey: FUEL_API_KEY
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/vincario/apikey
    secretKey: VINCARIO_API_KEY
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/vincario/apisecret
    secretKey: VINCARIO_API_SECRET
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-secret-store
  target:
    name: {{ include "device-definitions-api.fullname" . }}-secret
    template:
      metadata: {}
