apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ include "device-definitions-api.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  backendType: secretsManager
  data:
    - key: {{ .Release.Namespace }}/definitions/db/host
      name: DB_HOST
    - key: {{ .Release.Namespace }}/definitions/db/user
      name: DB_USER
    - key: {{ .Release.Namespace }}/definitions/db/pass
      name: DB_PASSWORD
    - key: {{ .Release.Namespace }}/devices/redis/host
      name: REDIS_HOST
    - key: {{ .Release.Namespace }}/devices/redis/url
      name: REDIS_URL
    - key: {{ .Release.Namespace }}/devices/redis/password
      name: REDIS_PASSWORD
    - key: {{ .Release.Namespace }}/devices/elastic/appsearch/host
      name: ELASTIC_SEARCH_APP_SEARCH_HOST
    - key: {{ .Release.Namespace }}/devices/elastic/appsearch/token
      name: ELASTIC_SEARCH_APP_SEARCH_TOKEN
    - key: {{ .Release.Namespace }}/devices/elastic/analytics/host
      name: ELASTIC_SEARCH_ANALYTICS_HOST
    - key: {{ .Release.Namespace }}/devices/elastic/analytics/username
      name: ELASTIC_SEARCH_ANALYTICS_USERNAME
    - key: {{ .Release.Namespace }}/devices/elastic/analytics/password
      name: ELASTIC_SEARCH_ANALYTICS_PASSWORD
    - key: {{ .Release.Namespace }}/devices/drivly/apikey
      name: DRIVLY_API_KEY
