// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: pkg/grpc/device_definition.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDeviceDefinitionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *GetDeviceDefinitionRequest) Reset() {
	*x = GetDeviceDefinitionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_device_definition_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDeviceDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceDefinitionRequest) ProtoMessage() {}

func (x *GetDeviceDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_device_definition_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceDefinitionRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_device_definition_proto_rawDescGZIP(), []int{0}
}

func (x *GetDeviceDefinitionRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetDeviceDefinitionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceDefinitions []*GetDeviceDefinitionItemResponse `protobuf:"bytes,1,rep,name=device_definitions,json=deviceDefinitions,proto3" json:"device_definitions,omitempty"`
}

func (x *GetDeviceDefinitionResponse) Reset() {
	*x = GetDeviceDefinitionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_device_definition_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDeviceDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceDefinitionResponse) ProtoMessage() {}

func (x *GetDeviceDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_device_definition_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceDefinitionResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_device_definition_proto_rawDescGZIP(), []int{1}
}

func (x *GetDeviceDefinitionResponse) GetDeviceDefinitions() []*GetDeviceDefinitionItemResponse {
	if x != nil {
		return x.DeviceDefinitions
	}
	return nil
}

type GetDeviceDefinitionItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceDefinitionId     string                                                    `protobuf:"bytes,1,opt,name=device_definition_id,json=deviceDefinitionId,proto3" json:"device_definition_id,omitempty"`
	Name                   string                                                    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImageUrl               string                                                    `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	CompatibleIntegrations []*GetDeviceDefinitionItemResponse_CompatibleIntegrations `protobuf:"bytes,4,rep,name=compatible_integrations,json=compatibleIntegrations,proto3" json:"compatible_integrations,omitempty"`
	Type                   *GetDeviceDefinitionItemResponse_Type                     `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	VehicleData            *VehicleInfo                                              `protobuf:"bytes,6,opt,name=vehicle_data,json=vehicleData,proto3" json:"vehicle_data,omitempty"`
	Verified               bool                                                      `protobuf:"varint,7,opt,name=verified,proto3" json:"verified,omitempty"`
	DeviceIntegrations     []*GetDeviceDefinitionItemResponse_DeviceIntegrations     `protobuf:"bytes,8,rep,name=device_integrations,json=deviceIntegrations,proto3" json:"device_integrations,omitempty"`
	Make                   *GetDeviceDefinitionItemResponse_Make                     `protobuf:"bytes,9,opt,name=make,proto3" json:"make,omitempty"`
}

func (x *GetDeviceDefinitionItemResponse) Reset() {
	*x = GetDeviceDefinitionItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_device_definition_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDeviceDefinitionItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceDefinitionItemResponse) ProtoMessage() {}

func (x *GetDeviceDefinitionItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_device_definition_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceDefinitionItemResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceDefinitionItemResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_device_definition_proto_rawDescGZIP(), []int{2}
}

func (x *GetDeviceDefinitionItemResponse) GetDeviceDefinitionId() string {
	if x != nil {
		return x.DeviceDefinitionId
	}
	return ""
}

func (x *GetDeviceDefinitionItemResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetDeviceDefinitionItemResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *GetDeviceDefinitionItemResponse) GetCompatibleIntegrations() []*GetDeviceDefinitionItemResponse_CompatibleIntegrations {
	if x != nil {
		return x.CompatibleIntegrations
	}
	return nil
}

func (x *GetDeviceDefinitionItemResponse) GetType() *GetDeviceDefinitionItemResponse_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *GetDeviceDefinitionItemResponse) GetVehicleData() *VehicleInfo {
	if x != nil {
		return x.VehicleData
	}
	return nil
}

func (x *GetDeviceDefinitionItemResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *GetDeviceDefinitionItemResponse) GetDeviceIntegrations() []*GetDeviceDefinitionItemResponse_DeviceIntegrations {
	if x != nil {
		return x.DeviceIntegrations
	}
	return nil
}

func (x *GetDeviceDefinitionItemResponse) GetMake() *GetDeviceDefinitionItemResponse_Make {
	if x != nil {
		return x.Make
	}
	return nil
}

type VehicleInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FuelType            string  `protobuf:"bytes,1,opt,name=fuel_type,json=fuelType,proto3" json:"fuel_type,omitempty"`
	DrivenWheels        string  `protobuf:"bytes,2,opt,name=driven_wheels,json=drivenWheels,proto3" json:"driven_wheels,omitempty"`
	NumberOfDoors       int32   `protobuf:"varint,3,opt,name=number_of_doors,json=numberOfDoors,proto3" json:"number_of_doors,omitempty"`
	Base_MSRP           int32   `protobuf:"varint,4,opt,name=base_MSRP,json=baseMSRP,proto3" json:"base_MSRP,omitempty"`
	EPAClass            string  `protobuf:"bytes,5,opt,name=EPA_class,json=EPAClass,proto3" json:"EPA_class,omitempty"`
	VehicleType         string  `protobuf:"bytes,6,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	MPGHighway          float32 `protobuf:"fixed32,7,opt,name=MPG_highway,json=MPGHighway,proto3" json:"MPG_highway,omitempty"`
	MPGCity             float32 `protobuf:"fixed32,8,opt,name=MPG_city,json=MPGCity,proto3" json:"MPG_city,omitempty"`
	FuelTankCapacityGal float32 `protobuf:"fixed32,9,opt,name=fuel_tank_capacity_gal,json=fuelTankCapacityGal,proto3" json:"fuel_tank_capacity_gal,omitempty"`
	MPG                 float32 `protobuf:"fixed32,10,opt,name=MPG,proto3" json:"MPG,omitempty"`
}

func (x *VehicleInfo) Reset() {
	*x = VehicleInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_device_definition_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VehicleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleInfo) ProtoMessage() {}

func (x *VehicleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_device_definition_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleInfo.ProtoReflect.Descriptor instead.
func (*VehicleInfo) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_device_definition_proto_rawDescGZIP(), []int{3}
}

func (x *VehicleInfo) GetFuelType() string {
	if x != nil {
		return x.FuelType
	}
	return ""
}

func (x *VehicleInfo) GetDrivenWheels() string {
	if x != nil {
		return x.DrivenWheels
	}
	return ""
}

func (x *VehicleInfo) GetNumberOfDoors() int32 {
	if x != nil {
		return x.NumberOfDoors
	}
	return 0
}

func (x *VehicleInfo) GetBase_MSRP() int32 {
	if x != nil {
		return x.Base_MSRP
	}
	return 0
}

func (x *VehicleInfo) GetEPAClass() string {
	if x != nil {
		return x.EPAClass
	}
	return ""
}

func (x *VehicleInfo) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *VehicleInfo) GetMPGHighway() float32 {
	if x != nil {
		return x.MPGHighway
	}
	return 0
}

func (x *VehicleInfo) GetMPGCity() float32 {
	if x != nil {
		return x.MPGCity
	}
	return 0
}

func (x *VehicleInfo) GetFuelTankCapacityGal() float32 {
	if x != nil {
		return x.FuelTankCapacityGal
	}
	return 0
}

func (x *VehicleInfo) GetMPG() float32 {
	if x != nil {
		return x.MPG
	}
	return 0
}

type GetDeviceDefinitionByMMYRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Make   string `protobuf:"bytes,1,opt,name=make,proto3" json:"make,omitempty"`
	MakeID string `protobuf:"bytes,2,opt,name=makeID,proto3" json:"makeID,omitempty"`
	Model  string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Year   int32  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
}

func (x *GetDeviceDefinitionByMMYRequest) Reset() {
	*x = GetDeviceDefinitionByMMYRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_device_definition_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDeviceDefinitionByMMYRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceDefinitionByMMYRequest) ProtoMessage() {}

func (x *GetDeviceDefinitionByMMYRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_device_definition_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceDefinitionByMMYRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceDefinitionByMMYRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_device_definition_proto_rawDescGZIP(), []int{4}
}

func (x *GetDeviceDefinitionByMMYRequest) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *GetDeviceDefinitionByMMYRequest) GetMakeID() string {
	if x != nil {
		return x.MakeID
	}
	return ""
}

func (x *GetDeviceDefinitionByMMYRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GetDeviceDefinitionByMMYRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type GetIntegrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Integrations []*GetIntegrationItemResponse `protobuf:"bytes,1,rep,name=integrations,proto3" json:"integrations,omitempty"`
}

func (x *GetIntegrationResponse) Reset() {
	*x = GetIntegrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_device_definition_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIntegrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntegrationResponse) ProtoMessage() {}

func (x *GetIntegrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_device_definition_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntegrationResponse.ProtoReflect.Descriptor instead.
func (*GetIntegrationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_device_definition_proto_rawDescGZIP(), []int{5}
}

func (x *GetIntegrationResponse) GetIntegrations() []*GetIntegrationItemResponse {
	if x != nil {
		return x.Integrations
	}
	return nil
}

type EmptyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_device_definition_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_device_definition_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_device_definition_proto_rawDescGZIP(), []int{6}
}

type GetIntegrationItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type   string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Style  string `protobuf:"bytes,3,opt,name=style,proto3" json:"style,omitempty"`
	Vendor string `protobuf:"bytes,4,opt,name=vendor,proto3" json:"vendor,omitempty"`
}

func (x *GetIntegrationItemResponse) Reset() {
	*x = GetIntegrationItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_device_definition_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIntegrationItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntegrationItemResponse) ProtoMessage() {}

func (x *GetIntegrationItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_device_definition_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntegrationItemResponse.ProtoReflect.Descriptor instead.
func (*GetIntegrationItemResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_device_definition_proto_rawDescGZIP(), []int{7}
}

func (x *GetIntegrationItemResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetIntegrationItemResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetIntegrationItemResponse) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

func (x *GetIntegrationItemResponse) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

type GetDeviceDefinitionIntegrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Integrations []*GetDeviceDefinitionIntegrationItemResponse `protobuf:"bytes,1,rep,name=integrations,proto3" json:"integrations,omitempty"`
}

func (x *GetDeviceDefinitionIntegrationResponse) Reset() {
	*x = GetDeviceDefinitionIntegrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_device_definition_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDeviceDefinitionIntegrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceDefinitionIntegrationResponse) ProtoMessage() {}

func (x *GetDeviceDefinitionIntegrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_device_definition_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceDefinitionIntegrationResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceDefinitionIntegrationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_device_definition_proto_rawDescGZIP(), []int{8}
}

func (x *GetDeviceDefinitionIntegrationResponse) GetIntegrations() []*GetDeviceDefinitionIntegrationItemResponse {
	if x != nil {
		return x.Integrations
	}
	return nil
}

type GetDeviceDefinitionIntegrationItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type         string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Style        string `protobuf:"bytes,3,opt,name=style,proto3" json:"style,omitempty"`
	Vendor       string `protobuf:"bytes,4,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Region       string `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	Country      string `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	Capabilities string `protobuf:"bytes,7,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
}

func (x *GetDeviceDefinitionIntegrationItemResponse) Reset() {
	*x = GetDeviceDefinitionIntegrationItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_device_definition_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDeviceDefinitionIntegrationItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceDefinitionIntegrationItemResponse) ProtoMessage() {}

func (x *GetDeviceDefinitionIntegrationItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_device_definition_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceDefinitionIntegrationItemResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceDefinitionIntegrationItemResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_device_definition_proto_rawDescGZIP(), []int{9}
}

func (x *GetDeviceDefinitionIntegrationItemResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetDeviceDefinitionIntegrationItemResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetDeviceDefinitionIntegrationItemResponse) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

func (x *GetDeviceDefinitionIntegrationItemResponse) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *GetDeviceDefinitionIntegrationItemResponse) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GetDeviceDefinitionIntegrationItemResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GetDeviceDefinitionIntegrationItemResponse) GetCapabilities() string {
	if x != nil {
		return x.Capabilities
	}
	return ""
}

type GetDeviceDefinitionIntegrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetDeviceDefinitionIntegrationRequest) Reset() {
	*x = GetDeviceDefinitionIntegrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_device_definition_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDeviceDefinitionIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceDefinitionIntegrationRequest) ProtoMessage() {}

func (x *GetDeviceDefinitionIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_device_definition_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceDefinitionIntegrationRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceDefinitionIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_device_definition_proto_rawDescGZIP(), []int{10}
}

func (x *GetDeviceDefinitionIntegrationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateDeviceDefinitionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Make   string `protobuf:"bytes,1,opt,name=make,proto3" json:"make,omitempty"`
	Model  string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Year   int32  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Source string `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *CreateDeviceDefinitionRequest) Reset() {
	*x = CreateDeviceDefinitionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_device_definition_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDeviceDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeviceDefinitionRequest) ProtoMessage() {}

func (x *CreateDeviceDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_device_definition_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeviceDefinitionRequest.ProtoReflect.Descriptor instead.
func (*CreateDeviceDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_device_definition_proto_rawDescGZIP(), []int{11}
}

func (x *CreateDeviceDefinitionRequest) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *CreateDeviceDefinitionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateDeviceDefinitionRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CreateDeviceDefinitionRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type CreateDeviceDefinitionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateDeviceDefinitionResponse) Reset() {
	*x = CreateDeviceDefinitionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_device_definition_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDeviceDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeviceDefinitionResponse) ProtoMessage() {}

func (x *CreateDeviceDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_device_definition_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeviceDefinitionResponse.ProtoReflect.Descriptor instead.
func (*CreateDeviceDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_device_definition_proto_rawDescGZIP(), []int{12}
}

func (x *CreateDeviceDefinitionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateDeviceIntegrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceDefinitionId string `protobuf:"bytes,1,opt,name=device_definition_id,json=deviceDefinitionId,proto3" json:"device_definition_id,omitempty"`
	IntegrationId      string `protobuf:"bytes,2,opt,name=integration_id,json=integrationId,proto3" json:"integration_id,omitempty"`
	Region             string `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
}

func (x *CreateDeviceIntegrationRequest) Reset() {
	*x = CreateDeviceIntegrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_device_definition_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDeviceIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeviceIntegrationRequest) ProtoMessage() {}

func (x *CreateDeviceIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_device_definition_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeviceIntegrationRequest.ProtoReflect.Descriptor instead.
func (*CreateDeviceIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_device_definition_proto_rawDescGZIP(), []int{13}
}

func (x *CreateDeviceIntegrationRequest) GetDeviceDefinitionId() string {
	if x != nil {
		return x.DeviceDefinitionId
	}
	return ""
}

func (x *CreateDeviceIntegrationRequest) GetIntegrationId() string {
	if x != nil {
		return x.IntegrationId
	}
	return ""
}

func (x *CreateDeviceIntegrationRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type CreateDeviceIntegrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateDeviceIntegrationResponse) Reset() {
	*x = CreateDeviceIntegrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_device_definition_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDeviceIntegrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeviceIntegrationResponse) ProtoMessage() {}

func (x *CreateDeviceIntegrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_device_definition_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeviceIntegrationResponse.ProtoReflect.Descriptor instead.
func (*CreateDeviceIntegrationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_device_definition_proto_rawDescGZIP(), []int{14}
}

func (x *CreateDeviceIntegrationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateDeviceDefinitionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceDefinitionId string       `protobuf:"bytes,1,opt,name=device_definition_id,json=deviceDefinitionId,proto3" json:"device_definition_id,omitempty"`
	VehicleData        *VehicleInfo `protobuf:"bytes,2,opt,name=vehicle_data,json=vehicleData,proto3" json:"vehicle_data,omitempty"`
}

func (x *UpdateDeviceDefinitionRequest) Reset() {
	*x = UpdateDeviceDefinitionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_device_definition_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDeviceDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceDefinitionRequest) ProtoMessage() {}

func (x *UpdateDeviceDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_device_definition_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceDefinitionRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeviceDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_device_definition_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateDeviceDefinitionRequest) GetDeviceDefinitionId() string {
	if x != nil {
		return x.DeviceDefinitionId
	}
	return ""
}

func (x *UpdateDeviceDefinitionRequest) GetVehicleData() *VehicleInfo {
	if x != nil {
		return x.VehicleData
	}
	return nil
}

type UpdateDeviceDefinitionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UpdateDeviceDefinitionResponse) Reset() {
	*x = UpdateDeviceDefinitionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_device_definition_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDeviceDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceDefinitionResponse) ProtoMessage() {}

func (x *UpdateDeviceDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_device_definition_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceDefinitionResponse.ProtoReflect.Descriptor instead.
func (*UpdateDeviceDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_device_definition_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateDeviceDefinitionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDeviceDefinitionItemResponse_CompatibleIntegrations struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type         string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Style        string `protobuf:"bytes,3,opt,name=style,proto3" json:"style,omitempty"`
	Vendor       string `protobuf:"bytes,4,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Region       string `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	Country      string `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	Capabilities string `protobuf:"bytes,7,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
}

func (x *GetDeviceDefinitionItemResponse_CompatibleIntegrations) Reset() {
	*x = GetDeviceDefinitionItemResponse_CompatibleIntegrations{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_device_definition_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDeviceDefinitionItemResponse_CompatibleIntegrations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceDefinitionItemResponse_CompatibleIntegrations) ProtoMessage() {}

func (x *GetDeviceDefinitionItemResponse_CompatibleIntegrations) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_device_definition_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceDefinitionItemResponse_CompatibleIntegrations.ProtoReflect.Descriptor instead.
func (*GetDeviceDefinitionItemResponse_CompatibleIntegrations) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_device_definition_proto_rawDescGZIP(), []int{2, 0}
}

func (x *GetDeviceDefinitionItemResponse_CompatibleIntegrations) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetDeviceDefinitionItemResponse_CompatibleIntegrations) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetDeviceDefinitionItemResponse_CompatibleIntegrations) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

func (x *GetDeviceDefinitionItemResponse_CompatibleIntegrations) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *GetDeviceDefinitionItemResponse_CompatibleIntegrations) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GetDeviceDefinitionItemResponse_CompatibleIntegrations) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GetDeviceDefinitionItemResponse_CompatibleIntegrations) GetCapabilities() string {
	if x != nil {
		return x.Capabilities
	}
	return ""
}

type GetDeviceDefinitionItemResponse_Type struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Make      string   `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Model     string   `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Year      int32    `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	SubModels []string `protobuf:"bytes,5,rep,name=sub_models,json=subModels,proto3" json:"sub_models,omitempty"`
}

func (x *GetDeviceDefinitionItemResponse_Type) Reset() {
	*x = GetDeviceDefinitionItemResponse_Type{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_device_definition_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDeviceDefinitionItemResponse_Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceDefinitionItemResponse_Type) ProtoMessage() {}

func (x *GetDeviceDefinitionItemResponse_Type) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_device_definition_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceDefinitionItemResponse_Type.ProtoReflect.Descriptor instead.
func (*GetDeviceDefinitionItemResponse_Type) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_device_definition_proto_rawDescGZIP(), []int{2, 1}
}

func (x *GetDeviceDefinitionItemResponse_Type) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetDeviceDefinitionItemResponse_Type) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *GetDeviceDefinitionItemResponse_Type) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GetDeviceDefinitionItemResponse_Type) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetDeviceDefinitionItemResponse_Type) GetSubModels() []string {
	if x != nil {
		return x.SubModels
	}
	return nil
}

type GetDeviceDefinitionItemResponse_DeviceIntegrations struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type         string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Style        string `protobuf:"bytes,3,opt,name=style,proto3" json:"style,omitempty"`
	Vendor       string `protobuf:"bytes,4,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Region       string `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	Country      string `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	Capabilities string `protobuf:"bytes,7,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
}

func (x *GetDeviceDefinitionItemResponse_DeviceIntegrations) Reset() {
	*x = GetDeviceDefinitionItemResponse_DeviceIntegrations{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_device_definition_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDeviceDefinitionItemResponse_DeviceIntegrations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceDefinitionItemResponse_DeviceIntegrations) ProtoMessage() {}

func (x *GetDeviceDefinitionItemResponse_DeviceIntegrations) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_device_definition_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceDefinitionItemResponse_DeviceIntegrations.ProtoReflect.Descriptor instead.
func (*GetDeviceDefinitionItemResponse_DeviceIntegrations) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_device_definition_proto_rawDescGZIP(), []int{2, 2}
}

func (x *GetDeviceDefinitionItemResponse_DeviceIntegrations) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetDeviceDefinitionItemResponse_DeviceIntegrations) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetDeviceDefinitionItemResponse_DeviceIntegrations) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

func (x *GetDeviceDefinitionItemResponse_DeviceIntegrations) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *GetDeviceDefinitionItemResponse_DeviceIntegrations) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GetDeviceDefinitionItemResponse_DeviceIntegrations) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GetDeviceDefinitionItemResponse_DeviceIntegrations) GetCapabilities() string {
	if x != nil {
		return x.Capabilities
	}
	return ""
}

type GetDeviceDefinitionItemResponse_Make struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LogUrl          string `protobuf:"bytes,3,opt,name=log_url,json=logUrl,proto3" json:"log_url,omitempty"`
	OemPlatformName string `protobuf:"bytes,4,opt,name=oem_platform_name,json=oemPlatformName,proto3" json:"oem_platform_name,omitempty"`
}

func (x *GetDeviceDefinitionItemResponse_Make) Reset() {
	*x = GetDeviceDefinitionItemResponse_Make{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_device_definition_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDeviceDefinitionItemResponse_Make) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceDefinitionItemResponse_Make) ProtoMessage() {}

func (x *GetDeviceDefinitionItemResponse_Make) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_device_definition_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceDefinitionItemResponse_Make.ProtoReflect.Descriptor instead.
func (*GetDeviceDefinitionItemResponse_Make) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_device_definition_proto_rawDescGZIP(), []int{2, 3}
}

func (x *GetDeviceDefinitionItemResponse_Make) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetDeviceDefinitionItemResponse_Make) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetDeviceDefinitionItemResponse_Make) GetLogUrl() string {
	if x != nil {
		return x.LogUrl
	}
	return ""
}

func (x *GetDeviceDefinitionItemResponse_Make) GetOemPlatformName() string {
	if x != nil {
		return x.OemPlatformName
	}
	return ""
}

var File_pkg_grpc_device_definition_proto protoreflect.FileDescriptor

var file_pkg_grpc_device_definition_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x2e, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x73, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x54, 0x0a, 0x12, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x11, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xa4, 0x09,
	0x0a, 0x1f, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x30, 0x0a, 0x14, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x64, 0x65, 0x66, 0x69,
	0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x12, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x55, 0x72, 0x6c, 0x12, 0x75, 0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x69, 0x62,
	0x6c, 0x65, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x6f, 0x6d,
	0x70, 0x61, 0x74, 0x69, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x16, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x69, 0x62, 0x6c, 0x65, 0x49,
	0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x3e, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x34, 0x0a, 0x0c, 0x76,
	0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x69, 0x0a,
	0x13, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x12, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x74, 0x65,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x3e, 0x0a, 0x04, 0x6d, 0x61, 0x6b, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65,
	0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4d, 0x61,
	0x6b, 0x65, 0x52, 0x04, 0x6d, 0x61, 0x6b, 0x65, 0x1a, 0xc0, 0x01, 0x0a, 0x16, 0x43, 0x6f, 0x6d,
	0x70, 0x61, 0x74, 0x69, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x79, 0x6c, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76,
	0x65, 0x6e, 0x64, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x61, 0x70, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63,
	0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x1a, 0x77, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x6b, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x6b, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x75, 0x62, 0x5f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x73, 0x75, 0x62, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x1a, 0xbc, 0x01, 0x0a, 0x12, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x73, 0x74, 0x79, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x22, 0x0a, 0x0c, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x1a, 0x6f, 0x0a, 0x04, 0x4d, 0x61, 0x6b, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x6c, 0x6f, 0x67, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6c, 0x6f, 0x67, 0x55, 0x72, 0x6c, 0x12, 0x2a, 0x0a, 0x11, 0x6f, 0x65, 0x6d, 0x5f,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x6f, 0x65, 0x6d, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0xd7, 0x02, 0x0a, 0x0b, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x75, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x65, 0x6c, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x72, 0x69, 0x76, 0x65, 0x6e, 0x5f, 0x77, 0x68, 0x65, 0x65,
	0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x72, 0x69, 0x76, 0x65, 0x6e,
	0x57, 0x68, 0x65, 0x65, 0x6c, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x5f, 0x6f, 0x66, 0x5f, 0x64, 0x6f, 0x6f, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0d, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x44, 0x6f, 0x6f, 0x72, 0x73, 0x12, 0x1b,
	0x0a, 0x09, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x4d, 0x53, 0x52, 0x50, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x62, 0x61, 0x73, 0x65, 0x4d, 0x53, 0x52, 0x50, 0x12, 0x1b, 0x0a, 0x09, 0x45,
	0x50, 0x41, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x45, 0x50, 0x41, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x76, 0x65, 0x68, 0x69,
	0x63, 0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x4d,
	0x50, 0x47, 0x5f, 0x68, 0x69, 0x67, 0x68, 0x77, 0x61, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x0a, 0x4d, 0x50, 0x47, 0x48, 0x69, 0x67, 0x68, 0x77, 0x61, 0x79, 0x12, 0x19, 0x0a, 0x08,
	0x4d, 0x50, 0x47, 0x5f, 0x63, 0x69, 0x74, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07,
	0x4d, 0x50, 0x47, 0x43, 0x69, 0x74, 0x79, 0x12, 0x33, 0x0a, 0x16, 0x66, 0x75, 0x65, 0x6c, 0x5f,
	0x74, 0x61, 0x6e, 0x6b, 0x5f, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x67, 0x61,
	0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x13, 0x66, 0x75, 0x65, 0x6c, 0x54, 0x61, 0x6e,
	0x6b, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x47, 0x61, 0x6c, 0x12, 0x10, 0x0a, 0x03,
	0x4d, 0x50, 0x47, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x4d, 0x50, 0x47, 0x22, 0x77,
	0x0a, 0x1f, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x4d, 0x4d, 0x59, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x6b, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6d, 0x61, 0x6b, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x6b, 0x65, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x6b, 0x65, 0x49, 0x44, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x22, 0x5e, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x49, 0x6e,
	0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x44, 0x0a, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47,
	0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6e, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x49, 0x6e,
	0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x79,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x22, 0x7e, 0x0a, 0x26, 0x47, 0x65, 0x74, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e,
	0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x54, 0x0a, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47,
	0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xd4, 0x01, 0x0a, 0x2a, 0x47, 0x65, 0x74, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74,
	0x79, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x79, 0x6c, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x61,
	0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0x37,
	0x0a, 0x25, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x75, 0x0a, 0x1d, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x6b, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x6b, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x30,
	0x0a, 0x1e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65,
	0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x91, 0x01, 0x0a, 0x1e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x14, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x64, 0x65,
	0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x12, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69,
	0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x67, 0x69, 0x6f, 0x6e, 0x22, 0x31, 0x0a, 0x1f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x87, 0x01, 0x0a, 0x1d, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x14, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44,
	0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x0c, 0x76,
	0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x22, 0x30, 0x0a, 0x1e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x32, 0xd7, 0x05, 0x0a, 0x17, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65,
	0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x5e, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69,
	0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x44, 0x12, 0x20, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x68, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69,
	0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x4d, 0x4d, 0x59, 0x12, 0x25, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69,
	0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x4d, 0x4d, 0x59, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x25, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x7b,
	0x0a, 0x1e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x2b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x74, 0x65, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65,
	0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63, 0x0a, 0x16, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65,
	0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x66, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x25, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x23, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x39, 0x5a,
	0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x44, 0x49, 0x4d, 0x4f,
	0x2d, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2d,
	0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2d, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_grpc_device_definition_proto_rawDescOnce sync.Once
	file_pkg_grpc_device_definition_proto_rawDescData = file_pkg_grpc_device_definition_proto_rawDesc
)

func file_pkg_grpc_device_definition_proto_rawDescGZIP() []byte {
	file_pkg_grpc_device_definition_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_device_definition_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_grpc_device_definition_proto_rawDescData)
	})
	return file_pkg_grpc_device_definition_proto_rawDescData
}

var file_pkg_grpc_device_definition_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_pkg_grpc_device_definition_proto_goTypes = []interface{}{
	(*GetDeviceDefinitionRequest)(nil),                             // 0: grpc.GetDeviceDefinitionRequest
	(*GetDeviceDefinitionResponse)(nil),                            // 1: grpc.GetDeviceDefinitionResponse
	(*GetDeviceDefinitionItemResponse)(nil),                        // 2: grpc.GetDeviceDefinitionItemResponse
	(*VehicleInfo)(nil),                                            // 3: grpc.VehicleInfo
	(*GetDeviceDefinitionByMMYRequest)(nil),                        // 4: grpc.GetDeviceDefinitionByMMYRequest
	(*GetIntegrationResponse)(nil),                                 // 5: grpc.GetIntegrationResponse
	(*EmptyRequest)(nil),                                           // 6: grpc.EmptyRequest
	(*GetIntegrationItemResponse)(nil),                             // 7: grpc.GetIntegrationItemResponse
	(*GetDeviceDefinitionIntegrationResponse)(nil),                 // 8: grpc.GetDeviceDefinitionIntegrationResponse
	(*GetDeviceDefinitionIntegrationItemResponse)(nil),             // 9: grpc.GetDeviceDefinitionIntegrationItemResponse
	(*GetDeviceDefinitionIntegrationRequest)(nil),                  // 10: grpc.GetDeviceDefinitionIntegrationRequest
	(*CreateDeviceDefinitionRequest)(nil),                          // 11: grpc.CreateDeviceDefinitionRequest
	(*CreateDeviceDefinitionResponse)(nil),                         // 12: grpc.CreateDeviceDefinitionResponse
	(*CreateDeviceIntegrationRequest)(nil),                         // 13: grpc.CreateDeviceIntegrationRequest
	(*CreateDeviceIntegrationResponse)(nil),                        // 14: grpc.CreateDeviceIntegrationResponse
	(*UpdateDeviceDefinitionRequest)(nil),                          // 15: grpc.UpdateDeviceDefinitionRequest
	(*UpdateDeviceDefinitionResponse)(nil),                         // 16: grpc.UpdateDeviceDefinitionResponse
	(*GetDeviceDefinitionItemResponse_CompatibleIntegrations)(nil), // 17: grpc.GetDeviceDefinitionItemResponse.CompatibleIntegrations
	(*GetDeviceDefinitionItemResponse_Type)(nil),                   // 18: grpc.GetDeviceDefinitionItemResponse.Type
	(*GetDeviceDefinitionItemResponse_DeviceIntegrations)(nil),     // 19: grpc.GetDeviceDefinitionItemResponse.DeviceIntegrations
	(*GetDeviceDefinitionItemResponse_Make)(nil),                   // 20: grpc.GetDeviceDefinitionItemResponse.Make
}
var file_pkg_grpc_device_definition_proto_depIdxs = []int32{
	2,  // 0: grpc.GetDeviceDefinitionResponse.device_definitions:type_name -> grpc.GetDeviceDefinitionItemResponse
	17, // 1: grpc.GetDeviceDefinitionItemResponse.compatible_integrations:type_name -> grpc.GetDeviceDefinitionItemResponse.CompatibleIntegrations
	18, // 2: grpc.GetDeviceDefinitionItemResponse.type:type_name -> grpc.GetDeviceDefinitionItemResponse.Type
	3,  // 3: grpc.GetDeviceDefinitionItemResponse.vehicle_data:type_name -> grpc.VehicleInfo
	19, // 4: grpc.GetDeviceDefinitionItemResponse.device_integrations:type_name -> grpc.GetDeviceDefinitionItemResponse.DeviceIntegrations
	20, // 5: grpc.GetDeviceDefinitionItemResponse.make:type_name -> grpc.GetDeviceDefinitionItemResponse.Make
	7,  // 6: grpc.GetIntegrationResponse.integrations:type_name -> grpc.GetIntegrationItemResponse
	9,  // 7: grpc.GetDeviceDefinitionIntegrationResponse.integrations:type_name -> grpc.GetDeviceDefinitionIntegrationItemResponse
	3,  // 8: grpc.UpdateDeviceDefinitionRequest.vehicle_data:type_name -> grpc.VehicleInfo
	0,  // 9: grpc.DeviceDefinitionService.GetDeviceDefinitionByID:input_type -> grpc.GetDeviceDefinitionRequest
	4,  // 10: grpc.DeviceDefinitionService.GetDeviceDefinitionByMMY:input_type -> grpc.GetDeviceDefinitionByMMYRequest
	6,  // 11: grpc.DeviceDefinitionService.GetIntegrations:input_type -> grpc.EmptyRequest
	10, // 12: grpc.DeviceDefinitionService.GetDeviceDefinitionIntegration:input_type -> grpc.GetDeviceDefinitionIntegrationRequest
	11, // 13: grpc.DeviceDefinitionService.CreateDeviceDefinition:input_type -> grpc.CreateDeviceDefinitionRequest
	13, // 14: grpc.DeviceDefinitionService.CreateDeviceIntegration:input_type -> grpc.CreateDeviceIntegrationRequest
	15, // 15: grpc.DeviceDefinitionService.UpdateDeviceDefinition:input_type -> grpc.UpdateDeviceDefinitionRequest
	1,  // 16: grpc.DeviceDefinitionService.GetDeviceDefinitionByID:output_type -> grpc.GetDeviceDefinitionResponse
	2,  // 17: grpc.DeviceDefinitionService.GetDeviceDefinitionByMMY:output_type -> grpc.GetDeviceDefinitionItemResponse
	5,  // 18: grpc.DeviceDefinitionService.GetIntegrations:output_type -> grpc.GetIntegrationResponse
	8,  // 19: grpc.DeviceDefinitionService.GetDeviceDefinitionIntegration:output_type -> grpc.GetDeviceDefinitionIntegrationResponse
	12, // 20: grpc.DeviceDefinitionService.CreateDeviceDefinition:output_type -> grpc.CreateDeviceDefinitionResponse
	14, // 21: grpc.DeviceDefinitionService.CreateDeviceIntegration:output_type -> grpc.CreateDeviceIntegrationResponse
	16, // 22: grpc.DeviceDefinitionService.UpdateDeviceDefinition:output_type -> grpc.UpdateDeviceDefinitionResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_pkg_grpc_device_definition_proto_init() }
func file_pkg_grpc_device_definition_proto_init() {
	if File_pkg_grpc_device_definition_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_grpc_device_definition_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDeviceDefinitionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_device_definition_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDeviceDefinitionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_device_definition_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDeviceDefinitionItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_device_definition_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VehicleInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_device_definition_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDeviceDefinitionByMMYRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_device_definition_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIntegrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_device_definition_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_device_definition_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIntegrationItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_device_definition_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDeviceDefinitionIntegrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_device_definition_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDeviceDefinitionIntegrationItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_device_definition_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDeviceDefinitionIntegrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_device_definition_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDeviceDefinitionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_device_definition_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDeviceDefinitionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_device_definition_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDeviceIntegrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_device_definition_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDeviceIntegrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_device_definition_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDeviceDefinitionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_device_definition_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDeviceDefinitionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_device_definition_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDeviceDefinitionItemResponse_CompatibleIntegrations); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_device_definition_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDeviceDefinitionItemResponse_Type); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_device_definition_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDeviceDefinitionItemResponse_DeviceIntegrations); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_device_definition_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDeviceDefinitionItemResponse_Make); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_grpc_device_definition_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_device_definition_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_device_definition_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_device_definition_proto_msgTypes,
	}.Build()
	File_pkg_grpc_device_definition_proto = out.File
	file_pkg_grpc_device_definition_proto_rawDesc = nil
	file_pkg_grpc_device_definition_proto_goTypes = nil
	file_pkg_grpc_device_definition_proto_depIdxs = nil
}
