// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: pkg/grpc/integration.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetIntegrationOptionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MakeId string `protobuf:"bytes,1,opt,name=make_id,json=makeId,proto3" json:"make_id,omitempty"`
}

func (x *GetIntegrationOptionsRequest) Reset() {
	*x = GetIntegrationOptionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_integration_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIntegrationOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntegrationOptionsRequest) ProtoMessage() {}

func (x *GetIntegrationOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_integration_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntegrationOptionsRequest.ProtoReflect.Descriptor instead.
func (*GetIntegrationOptionsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_integration_proto_rawDescGZIP(), []int{0}
}

func (x *GetIntegrationOptionsRequest) GetMakeId() string {
	if x != nil {
		return x.MakeId
	}
	return ""
}

type GetIntegrationOptionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IntegrationOptions []*GetIntegrationOptionItem `protobuf:"bytes,1,rep,name=integration_options,json=integrationOptions,proto3" json:"integration_options,omitempty"`
}

func (x *GetIntegrationOptionsResponse) Reset() {
	*x = GetIntegrationOptionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_integration_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIntegrationOptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntegrationOptionsResponse) ProtoMessage() {}

func (x *GetIntegrationOptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_integration_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntegrationOptionsResponse.ProtoReflect.Descriptor instead.
func (*GetIntegrationOptionsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_integration_proto_rawDescGZIP(), []int{1}
}

func (x *GetIntegrationOptionsResponse) GetIntegrationOptions() []*GetIntegrationOptionItem {
	if x != nil {
		return x.IntegrationOptions
	}
	return nil
}

type GetIntegrationOptionItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IntegrationId     string `protobuf:"bytes,1,opt,name=integration_id,json=integrationId,proto3" json:"integration_id,omitempty"`
	IntegrationVendor string `protobuf:"bytes,2,opt,name=integration_vendor,json=integrationVendor,proto3" json:"integration_vendor,omitempty"`
	Region            string `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
}

func (x *GetIntegrationOptionItem) Reset() {
	*x = GetIntegrationOptionItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_integration_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIntegrationOptionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntegrationOptionItem) ProtoMessage() {}

func (x *GetIntegrationOptionItem) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_integration_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntegrationOptionItem.ProtoReflect.Descriptor instead.
func (*GetIntegrationOptionItem) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_integration_proto_rawDescGZIP(), []int{2}
}

func (x *GetIntegrationOptionItem) GetIntegrationId() string {
	if x != nil {
		return x.IntegrationId
	}
	return ""
}

func (x *GetIntegrationOptionItem) GetIntegrationVendor() string {
	if x != nil {
		return x.IntegrationVendor
	}
	return ""
}

func (x *GetIntegrationOptionItem) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

var File_pkg_grpc_integration_proto protoreflect.FileDescriptor

var file_pkg_grpc_integration_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72,
	0x70, 0x63, 0x22, 0x37, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61, 0x6b, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x6b, 0x65, 0x49, 0x64, 0x22, 0x70, 0x0a, 0x1d, 0x47,
	0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x13,
	0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x12, 0x69, 0x6e, 0x74, 0x65, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x88, 0x01,
	0x0a, 0x18, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x6e,
	0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x2d, 0x0a, 0x12, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x69,
	0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x32, 0x76, 0x0a, 0x12, 0x49, 0x6e, 0x74, 0x65,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x60,
	0x0a, 0x15, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x22, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47,
	0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x44,
	0x49, 0x4d, 0x4f, 0x2d, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x2d, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2d, 0x61,
	0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pkg_grpc_integration_proto_rawDescOnce sync.Once
	file_pkg_grpc_integration_proto_rawDescData = file_pkg_grpc_integration_proto_rawDesc
)

func file_pkg_grpc_integration_proto_rawDescGZIP() []byte {
	file_pkg_grpc_integration_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_integration_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_grpc_integration_proto_rawDescData)
	})
	return file_pkg_grpc_integration_proto_rawDescData
}

var file_pkg_grpc_integration_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_grpc_integration_proto_goTypes = []interface{}{
	(*GetIntegrationOptionsRequest)(nil),  // 0: grpc.GetIntegrationOptionsRequest
	(*GetIntegrationOptionsResponse)(nil), // 1: grpc.GetIntegrationOptionsResponse
	(*GetIntegrationOptionItem)(nil),      // 2: grpc.GetIntegrationOptionItem
}
var file_pkg_grpc_integration_proto_depIdxs = []int32{
	2, // 0: grpc.GetIntegrationOptionsResponse.integration_options:type_name -> grpc.GetIntegrationOptionItem
	0, // 1: grpc.IntegrationService.GetIntegrationOptions:input_type -> grpc.GetIntegrationOptionsRequest
	1, // 2: grpc.IntegrationService.GetIntegrationOptions:output_type -> grpc.GetIntegrationOptionsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_grpc_integration_proto_init() }
func file_pkg_grpc_integration_proto_init() {
	if File_pkg_grpc_integration_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_grpc_integration_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIntegrationOptionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_integration_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIntegrationOptionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_integration_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIntegrationOptionItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_grpc_integration_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_integration_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_integration_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_integration_proto_msgTypes,
	}.Build()
	File_pkg_grpc_integration_proto = out.File
	file_pkg_grpc_integration_proto_rawDesc = nil
	file_pkg_grpc_integration_proto_goTypes = nil
	file_pkg_grpc_integration_proto_depIdxs = nil
}
