definitions:
  big.Int:
    type: object
  github_com_DIMO-Network_device-definitions-api_internal_core_models.DeviceIntegration:
    properties:
      features:
        items:
          $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_models.DeviceIntegrationFeature'
        type: array
      id:
        type: string
      region:
        type: string
      style:
        type: string
      type:
        type: string
      vendor:
        type: string
    type: object
  github_com_DIMO-Network_device-definitions-api_internal_core_models.DeviceIntegrationFeature:
    properties:
      featureKey:
        type: string
      supportLevel:
        type: integer
    type: object
  github_com_DIMO-Network_device-definitions-api_internal_core_models.DeviceMake:
    properties:
      external_ids:
        items:
          type: integer
        type: array
      externalIdsTyped:
        items:
          $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_models.ExternalID'
        type: array
      hardware_template_id:
        $ref: '#/definitions/null.String'
      id:
        type: string
      logo_url:
        $ref: '#/definitions/null.String'
      metadata:
        items:
          type: integer
        type: array
      metadataTyped:
        $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_models.DeviceMakeMetadata'
      name:
        type: string
      nameSlug:
        type: string
      oem_platform_name:
        $ref: '#/definitions/null.String'
      tokenId:
        $ref: '#/definitions/big.Int'
    type: object
  github_com_DIMO-Network_device-definitions-api_internal_core_models.DeviceMakeMetadata:
    properties:
      ride_guide_link:
        type: string
    type: object
  github_com_DIMO-Network_device-definitions-api_internal_core_models.DeviceStyle:
    properties:
      deviceDefinitionId:
        type: string
      externalStyleId:
        type: string
      hardware_template_id:
        type: string
      id:
        type: string
      name:
        type: string
      source:
        type: string
      subModel:
        type: string
    type: object
  github_com_DIMO-Network_device-definitions-api_internal_core_models.DeviceType:
    properties:
      make:
        type: string
      makeSlug:
        type: string
      model:
        type: string
      modelSlug:
        type: string
      subModels:
        items:
          type: string
        type: array
      type:
        description: Type is eg. Vehicle, E-bike, roomba
        type: string
      year:
        type: integer
    type: object
  github_com_DIMO-Network_device-definitions-api_internal_core_models.DeviceTypeAttribute:
    properties:
      description:
        type: string
      label:
        type: string
      name:
        type: string
      options:
        items:
          type: string
        type: array
      required:
        type: boolean
      type:
        type: string
      value:
        type: string
    type: object
  github_com_DIMO-Network_device-definitions-api_internal_core_models.ExternalID:
    properties:
      id:
        type: string
      vendor:
        type: string
    type: object
  github_com_DIMO-Network_device-definitions-api_internal_core_models.GetDeviceDefinitionQueryResult:
    properties:
      compatibleIntegrations:
        items:
          $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_models.DeviceIntegration'
        type: array
      deviceAttributes:
        items:
          $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_models.DeviceTypeAttribute'
        type: array
      deviceDefinitionId:
        type: string
      deviceIntegrations:
        description: DeviceIntegrations has integrations this vehicle can integrate
          with, from table device_integrations
        items:
          $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_models.DeviceIntegration'
        type: array
      deviceStyles:
        items:
          $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_models.DeviceStyle'
        type: array
      external_id:
        type: string
      externalIds:
        items:
          $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_models.ExternalID'
        type: array
      hardware_template_id:
        type: string
      imageUrl:
        type: string
      make:
        $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_models.DeviceMake'
      metadata: {}
      name:
        type: string
      source:
        type: string
      type:
        $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_models.DeviceType'
      vehicleData:
        $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_models.VehicleInfo'
      verified:
        type: boolean
    type: object
  github_com_DIMO-Network_device-definitions-api_internal_core_models.VehicleInfo:
    properties:
      base_msrp:
        type: integer
      driven_wheels:
        type: string
      epa_class:
        type: string
      fuel_tank_capacity_gal:
        type: string
      fuel_type:
        type: string
      mpg:
        type: string
      mpg_city:
        type: string
      mpg_highway:
        type: string
      number_of_doors:
        type: string
      vehicle_type:
        description: VehicleType PASSENGER CAR, from NHTSA
        type: string
    type: object
  github_com_DIMO-Network_device-definitions-api_pkg_grpc.DeviceMake:
    properties:
      external_ids:
        description: 'Deprecated: Do not use.'
        type: string
      external_ids_typed:
        items:
          $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_pkg_grpc.ExternalID'
        type: array
      hardware_template_id:
        type: string
      id:
        type: string
      logo_url:
        type: string
      metadata:
        $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_pkg_grpc.Metadata'
      name:
        type: string
      name_slug:
        type: string
      oem_platform_name:
        type: string
      token_id:
        type: integer
    type: object
  github_com_DIMO-Network_device-definitions-api_pkg_grpc.ExternalID:
    properties:
      id:
        type: string
      vendor:
        type: string
    type: object
  github_com_DIMO-Network_device-definitions-api_pkg_grpc.GetDeviceMakeResponse:
    properties:
      device_makes:
        items:
          $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_pkg_grpc.DeviceMake'
        type: array
    type: object
  github_com_DIMO-Network_device-definitions-api_pkg_grpc.Metadata:
    properties:
      RideGuideLink:
        type: string
    type: object
  null.String:
    properties:
      string:
        type: string
      valid:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /bulk-decode:
    post:
      consumes:
      - application/json
      description: decodes a list of VINs
      operationId: BulkDecodeVIN
      parameters:
      - description: vin array.
        in: body
        name: vins
        required: true
        schema:
          items:
            type: string
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: gets a list of decoded vins.
      tags:
      - device-definitions
  /bulk-decode/csv:
    post:
      consumes:
      - application/json
      description: decodes a list of VINs
      operationId: BulkDecodeVINCSV
      parameters:
      - description: vin array.
        in: body
        name: vins
        required: true
        schema:
          items:
            type: string
          type: array
      produces:
      - text/csv
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: gets a list of decoded vins in csv format.
      tags:
      - device-definitions
  /device-definitions:
    get:
      description: gets a specific device definition by make model and year.
      operationId: GetDeviceDefinitionByMMY
      parameters:
      - description: make
        in: query
        name: make
        required: true
        type: string
      - description: model
        in: query
        name: model
        required: true
        type: string
      - description: year
        in: query
        name: year
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_models.GetDeviceDefinitionQueryResult'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: gets a specific device definition by make model and year.
      tags:
      - device-definitions
  /device-definitions/{id}:
    get:
      description: gets a device definition
      operationId: GetDeviceDefinitionByID
      parameters:
      - description: device definition id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_models.GetDeviceDefinitionQueryResult'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: gets a device definition
      tags:
      - device-definitions
  /device-definitions/{id}/integrations:
    get:
      description: gets all the available integrations for a device definition. Includes
        the capabilities of the device with the integration
      operationId: GetDeviceIntegrationsByID
      parameters:
      - description: device definition id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: gets all the available integrations for a device definition.
      tags:
      - device-definitions
  /device-definitions/all:
    get:
      consumes:
      - application/json
      description: gets a device definition
      operationId: GetDeviceDefinitionAll
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: gets all device definitions by Makes, models, and years
      tags:
      - device-definitions
  /device-makes:
    get:
      description: gets all device makes
      operationId: GetDeviceMakes
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_pkg_grpc.GetDeviceMakeResponse'
        "500":
          description: Internal Server Error
      summary: gets all device makes
      tags:
      - device-definitions
  /device-types/{id}:
    get:
      description: gets a devices type with attributes
      operationId: GetDeviceTypesByID
      parameters:
      - description: device type id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: gets a device type.
      tags:
      - device-definitions
  /integrations:
    get:
      description: gets list of integrations we have defined.
      operationId: GetIntegrations
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: gets list of integrations we have defined.
      tags:
      - device-definitions
  /integrations/{id}:
    get:
      consumes:
      - application/json
      description: gets integration by id.
      operationId: GetIntegrationByID
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: gets integration by id.
      tags:
      - device-definitions
swagger: "2.0"
