definitions:
  big.Int:
    type: object
  github_com_DIMO-Network_device-definitions-api_internal_core_models.DeviceMake:
    properties:
      created_at:
        type: string
      id:
        type: string
      logo_url:
        $ref: '#/definitions/null.String'
      metadata:
        items:
          type: integer
        type: array
      metadataTyped:
        $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_models.DeviceMakeMetadata'
      name:
        type: string
      nameSlug:
        type: string
      oem_platform_name:
        $ref: '#/definitions/null.String'
      tokenId:
        $ref: '#/definitions/big.Int'
      updated_at:
        type: string
    type: object
  github_com_DIMO-Network_device-definitions-api_internal_core_models.DeviceMakeMetadata:
    properties:
      ride_guide_link:
        type: string
    type: object
  github_com_DIMO-Network_device-definitions-api_internal_core_models.DeviceStyle:
    properties:
      definitionId:
        type: string
      externalStyleId:
        type: string
      hardware_template_id:
        type: string
      id:
        type: string
      metadata:
        items:
          $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_models.DeviceTypeAttribute'
        type: array
      name:
        type: string
      source:
        type: string
      subModel:
        type: string
    type: object
  github_com_DIMO-Network_device-definitions-api_internal_core_models.DeviceTypeAttribute:
    properties:
      description:
        type: string
      label:
        type: string
      name:
        type: string
      options:
        items:
          type: string
        type: array
      required:
        type: boolean
      type:
        type: string
      value:
        type: string
    type: object
  github_com_DIMO-Network_device-definitions-api_internal_core_models.GetDeviceDefinitionQueryResult:
    properties:
      deviceAttributes:
        items:
          $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_models.DeviceTypeAttribute'
        type: array
      deviceDefinitionId:
        type: string
      deviceStyles:
        items:
          $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_models.DeviceStyle'
        type: array
      hardware_template_id:
        type: string
      imageUrl:
        type: string
      make:
        $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_models.DeviceMake'
      metadata:
        items:
          type: integer
        type: array
      name:
        type: string
      nameSlug:
        type: string
      transactions:
        items:
          type: string
        type: array
      verified:
        type: boolean
    type: object
  github_com_DIMO-Network_device-definitions-api_internal_core_queries.CompatibilitySheetRow:
    properties:
      compatible:
        type: string
      definitionId:
        type: string
      make:
        type: string
      model:
        type: string
      year:
        type: integer
    type: object
  github_com_DIMO-Network_device-definitions-api_internal_core_queries.GetAllDeviceDefinitionBySearchQueryResult:
    properties:
      deviceDefinitions:
        items:
          $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_queries.GetAllDeviceDefinitionItem'
        type: array
      facets:
        $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_queries.GetAllDeviceDefinitionFacet'
      pagination:
        $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_queries.GetAllDeviceDefinitionPagination'
    type: object
  github_com_DIMO-Network_device-definitions-api_internal_core_queries.GetAllDeviceDefinitionFacet:
    properties:
      makes:
        items:
          $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_queries.GetAllDeviceDefinitionFacetItem'
        type: array
      models:
        items:
          $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_queries.GetAllDeviceDefinitionFacetItem'
        type: array
      years:
        items:
          $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_queries.GetAllDeviceDefinitionFacetItem'
        type: array
    type: object
  github_com_DIMO-Network_device-definitions-api_internal_core_queries.GetAllDeviceDefinitionFacetItem:
    properties:
      count:
        type: integer
      name:
        type: string
    type: object
  github_com_DIMO-Network_device-definitions-api_internal_core_queries.GetAllDeviceDefinitionItem:
    properties:
      id:
        type: string
      imageUrl:
        type: string
      legacy_ksuid:
        description: nolint
        type: string
      make:
        type: string
      model:
        description: ManufacturerTokenID int    `json:"manufacturerTokenId"` // todo
        type: string
      name:
        type: string
      year:
        type: integer
    type: object
  github_com_DIMO-Network_device-definitions-api_internal_core_queries.GetAllDeviceDefinitionPagination:
    properties:
      page:
        type: integer
      pageSize:
        type: integer
      totalItems:
        type: integer
      totalPages:
        type: integer
    type: object
  github_com_DIMO-Network_device-definitions-api_internal_core_queries.GetR1CompatibilitySearchQueryResult:
    properties:
      deviceDefinitions:
        items:
          $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_queries.GetR1SearchEntryItem'
        type: array
      pagination:
        $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_queries.GetAllDeviceDefinitionPagination'
    type: object
  github_com_DIMO-Network_device-definitions-api_internal_core_queries.GetR1SearchEntryItem:
    properties:
      compatible:
        type: string
      id:
        description: nolint
        type: string
      make:
        type: string
      model:
        type: string
      name:
        type: string
      year:
        type: integer
    type: object
  github_com_DIMO-Network_device-definitions-api_internal_infrastructure_gateways.DeviceDefinitionMetadata:
    properties:
      device_attributes:
        items:
          $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_infrastructure_gateways.DeviceTypeAttribute'
        type: array
    type: object
  github_com_DIMO-Network_device-definitions-api_internal_infrastructure_gateways.DeviceDefinitionTablelandModel:
    properties:
      devicetype:
        type: string
      id:
        type: string
      imageuri:
        type: string
      ksuid:
        type: string
      metadata:
        $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_infrastructure_gateways.DeviceDefinitionMetadata'
      model:
        type: string
      year:
        type: integer
    type: object
  github_com_DIMO-Network_device-definitions-api_internal_infrastructure_gateways.DeviceTypeAttribute:
    properties:
      name:
        type: string
      value:
        type: string
    type: object
  internal_api_handlers.DecodeVINRequest:
    properties:
      countryCode:
        description: 3 letter ISO
        type: string
      vin:
        type: string
    type: object
  internal_api_handlers.DecodeVINResponse:
    properties:
      deviceDefinitionId:
        description: new name slug based id, can use this to query identity-api
        type: string
      newTransactionHash:
        description: if a new device definition was created, the tableland transaction
          hash from the insert statement. Check this has completed before querying
          the ID
        type: string
    type: object
  null.String:
    properties:
      string:
        type: string
      valid:
        type: boolean
    type: object
info:
  contact: {}
  title: DIMO Device Definitions API
  version: "1.0"
paths:
  /compatibility/r1-sheet:
    get:
      description: gets r1 MMY compatibility google sheet in JSON form. returns an
        array of below objects
      operationId: GetCompatibilityR1Sheet
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_queries.CompatibilitySheetRow'
        "500":
          description: Internal Server Error
      summary: gets r1 MMY compatibility google sheet in JSON form
      tags:
      - device-definitions
  /device-definitions/{id}:
    get:
      description: gets a device definition
      operationId: GetDeviceDefinitionByID
      parameters:
      - description: device definition id or mmy definition_id eg. ford_escape_2020
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_infrastructure_gateways.DeviceDefinitionTablelandModel'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: gets a device definition, optionally from tableland (on-chain records)
        if use an mmy style id.
      tags:
      - device-definitions
  /device-definitions/decode-vin:
    post:
      consumes:
      - application/json
      description: decode a vin
      operationId: DecodeVIN
      parameters:
      - description: Decode VIN request
        in: body
        name: decodeRequest
        required: true
        schema:
          $ref: '#/definitions/internal_api_handlers.DecodeVINRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Response with definition ID.
          schema:
            $ref: '#/definitions/internal_api_handlers.DecodeVINResponse'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: returns device definition id corresponding to a given vin
      tags:
      - device-definitions
  /device-definitions/search:
    get:
      consumes:
      - application/json
      description: gets a device definition by search filter
      operationId: GetDeviceDefinitionSearch
      parameters:
      - description: query filter
        in: query
        name: query
        required: true
        type: string
      - description: make Slug
        in: query
        name: makeSlug
        type: string
      - description: model Slug
        in: query
        name: modelSlug
        type: string
      - description: year
        in: query
        name: year
        type: number
      - description: page
        in: query
        name: page
        type: number
      - description: pageSize
        in: query
        name: pageSize
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_queries.GetAllDeviceDefinitionBySearchQueryResult'
        "500":
          description: Internal Server Error
      summary: gets device definitions by search filter
      tags:
      - device-definitions
  /device-definitions/search-r1:
    get:
      consumes:
      - application/json
      description: gets r1 compatibility search by filter
      operationId: GetR1CompatibilitySearch
      parameters:
      - description: query filter
        in: query
        name: query
        required: true
        type: string
      - description: page
        in: query
        name: page
        type: number
      - description: pageSize
        in: query
        name: pageSize
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_queries.GetR1CompatibilitySearchQueryResult'
        "500":
          description: Internal Server Error
      summary: gets r1 MMY compatibility by search filter
      tags:
      - device-definitions
  /device-types:
    get:
      description: gets a devices type
      operationId: GetDeviceTypes
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: gets a device type.
      tags:
      - device-definitions
  /device-types/{id}:
    get:
      description: gets a devices type with attributes
      operationId: GetDeviceTypesByID
      parameters:
      - description: device type id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: gets a device type.
      tags:
      - device-definitions
  /integrations:
    get:
      description: gets list of integrations we have defined.
      operationId: GetIntegrations
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: gets list of integrations we have defined.
      tags:
      - device-definitions
  /integrations/{id}:
    get:
      consumes:
      - application/json
      description: gets integration by id.
      operationId: GetIntegrationByID
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: gets integration by id.
      tags:
      - device-definitions
  /manufacturers/integrations/smartcar:
    get:
      description: gets manufacturers supported by smartcar
      operationId: GetSmartcarManufacturers
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: gets all supported manufacturers for the smartcar external integration
      tags:
      - device-definitions
  /v2/device-definitions/{make}/{id}:
    get:
      description: gets a device definition
      operationId: GetDeviceDefinitionV2ByID
      parameters:
      - description: device make name
        in: path
        name: make
        required: true
        type: string
      - description: device definition id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_DIMO-Network_device-definitions-api_internal_core_models.GetDeviceDefinitionQueryResult'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: gets a device definition from tableland (on-chain records)
      tags:
      - device-definitions
  /v2/device-definitions/{make}/all:
    get:
      consumes:
      - application/json
      description: gets a device definition
      operationId: GetDeviceDefinitionV2All
      parameters:
      - description: device make name
        in: path
        name: make
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: gets all device definitions by Makes, models, and years, from tableland
        (on-chain records)
      tags:
      - device-definitions
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
