nameOverride: ''
fullnameOverride: ''
replicaCount: 2
image:
  repository: dimozone/device-definitions-api
  pullPolicy: IfNotPresent
  tag: 9f4c657
env:
  ENVIRONMENT: prod
  PORT: '8080'
  LOG_LEVEL: info
  DB_PORT: '5432'
  DB_NAME: device_definitions_api
  DB_MAX_OPEN_CONNECTIONS: '50'
  DB_MAX_IDLE_CONNECTIONS: '15'
  SERVICE_NAME: device-definitions-api
  JWT_KEY_SET_URL: https://auth.dimo.zone/keys
  DEPLOYMENT_BASE_URL: https://device-definitions-api.dimo.zone
  REDIS_USER: default
  REDIS_CLUSTER_MODE: true
  REDIS_TLS: true
  KAFKA_BROKERS: kafka-prod-dimo-kafka-kafka-brokers:9092
  ETHEREUM_SEND_TRANSACTION: true
  TABLELAND_API_GATEWAY: https://tableland.network/
  ETHEREUM_REGISTRY_ADDRESS: '0xFA8beC73cebB9D88FF88a2f75E7D7312f2Fd39EC'
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-secret: ingress/cf-origin-ca
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-origin: https://app.dimo.zone
    nginx.ingress.kubernetes.io/limit-rps: '9'
    external-dns.alpha.kubernetes.io/hostname: device-definitions-api.dimo.zone
  hosts:
    - host: device-definitions-api.dimo.zone
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 1
jobs:
  - name: search-index-load
    schedule: 0 0 * * 1
    args:
      - '-c'
      - /device-definitions-api sync -search-sync-dds; CODE=$?; echo "weekly elastic mmy search index sync completed"; wget -q --post-data "hello=shutdown" http://localhost:4191/shutdown &> /dev/null; exit $CODE;
  - name: feat-compat-updte
    schedule: 0 0 * * 0
    args:
      - '-c'
      - /device-definitions-api populate-device-features; CODE=$?; echo "weekly integration features update completed"; wget -q --post-data "hello=shutdown" http://localhost:4191/shutdown &> /dev/null; exit $CODE;
